// {
//     "addresses": [],
//     "cart": [
//         {
//             "id": 124693,
//             "account_id": 329836,
//             "cookie": null,
//             "product_id": 37657,
//             "in_hands_date": null,
//             "imprint_comment": "",
//             "quantity": 100,
//             "item_text": "",
//             "surface_color_id": 140418,
//             "product_option_id": 208220,
//             "delivery_instructions": "",
//             "design_help": false,
//             "special_instructions": null,
//             "additional_instructions": "",
//             "zip": "48104",
//             "estimated_shipping": 23.06,
//             "sales_tax": null,
//             "create_date": "2025-03-11T19:11:00.910Z",
//             "update_date": "2025-03-11T19:11:00.910Z",
//             "is_sample_product": false,
//             "imprint_colors": [],
//             "surface_color": {
//                 "id": 140418,
//                 "create_date": "2016-06-28T16:13:18.149Z",
//                 "update_date": "2017-03-30T20:05:27.125Z",
//                 "name": "Full Color",
//                 "upcharge": "0.000",
//                 "palette_id": 27348,
//                 "show_first": false,
//                 "deleted": false,
//                 "rgb": [
//                     "ffffff"
//                 ],
//                 "search_ids": [
//                     4,
//                     30
//                 ]
//             },
//             "product": {
//                 "id": 37657,
//                 "store": "regular_website",
//                 "wl_partner_id": null,
//                 "master_item_sku": "",
//                 "parent_product_id": null,
//                 "short_desc": "Keep attendees cool at outdoor events and advertise with our custom printed bread slice shaped hand fans! Printed on high density 22 pt. paper board with film lamination for added durability. 8\" fan stick is glued to the backside.  ",
//                 "long_desc": "Promote at your restaurant, music venues,  charity events and more with these vibrant full color printed hand fans!  One of our most popular hand fans, both sides are printed in full color with film lamination for a lasting message. Give us a call now and make your event more festive with these printed bread slice hand fans!",
//                 "special_notes": "Please note: We cannot print borders on digital full color fans.\n\nDesign art to allow for a glued 8” wooden handle on backside of fan.\n\nNeed your custom hand fans in 3 days or less? Check out our selection of 24-Hour Hand Fans or call our Customer Service Department for information.\n\nA single sided economy option is available. Please call for more information. ",
//                 "imprint_palette_id": null,
//                 "spin_url": null,
//                 "surface_palette_id": 27348,
//                 "update_date": "2025-03-10T18:58:05.669Z",
//                 "create_date": "2016-01-27T22:57:08.000Z",
//                 "name": "Full Color Econo Bread Slice Hand Fans",
//                 "url_name": "full-color-bread-slice-hand-fans-low-minimum-econo",
//                 "url_name_prev": null,
//                 "url_canonical": "/hand-fans/full-color-hand-fans/full-color-hand-fans/full-color-bread-slice-hand-fans-low-minimum-econo",
//                 "tracking_script": null,
//                 "blank_discount": 0,
//                 "size": "8\"",
//                 "wrap_size": null,
//                 "over_under_run": 10,
//                 "material": "High density 22 pt. white paper poster board",
//                 "print_method": "Offset Printing",
//                 "fine_print": null,
//                 "search_boost": "100",
//                 "quantities": [
//                     100,
//                     250,
//                     500,
//                     1000,
//                     2500,
//                     5000,
//                     10000
//                 ],
//                 "base_prices": [
//                     1.54,
//                     1.28,
//                     0.83,
//                     0.73,
//                     0.69,
//                     0.66,
//                     0.66
//                 ],
//                 "multiplier_prices": [
//                     0,
//                     0,
//                     0,
//                     0,
//                     0,
//                     0,
//                     0
//                 ],
//                 "price_model": "per color per side",
//                 "setup_fee": "40.00",
//                 "reorder_fee": "0.00",
//                 "custom_pms_fee": null,
//                 "production_time_min": 5,
//                 "production_time_max": 7,
//                 "production_time": "5-7",
//                 "production_time_units": "Days",
//                 "imprint_width": "0.0000",
//                 "imprint_height": "0.0000",
//                 "imprint_diameter": "0.0000",
//                 "min_order": 100,
//                 "min_order_units": "Fan",
//                 "order_increment": 1,
//                 "active": "Active",
//                 "active_status_text": "Lioncircle has waived the set-up on this item for PrintGlobe only.",
//                 "sub_category_id": 769,
//                 "display_order": 1,
//                 "meta_title": "Full Color Econo Bread Slice Hand Fans",
//                 "meta_description": "Full Color Econo Bread Slice Hand Fans - Low prices and the most helpful service you'll find! Custom printing is our specialty.",
//                 "public_sku": "FAN0243",
//                 "vendor_item_num": "P-LF- 20",
//                 "exact_vendor_sku": "LF-20",
//                 "single_imprint_font_id": null,
//                 "price_units": 1,
//                 "quantity_per_box": 300,
//                 "weight_per_box": "19.0000",
//                 "box_size_dimension_1": "12.0000",
//                 "box_size_dimension_2": "13.0000",
//                 "box_size_dimension_3": "20.0000",
//                 "vendor_id": 414,
//                 "clearance": false,
//                 "avail_blank": false,
//                 "setup_type": "One-Time",
//                 "reorder_type": "One-Time",
//                 "full_bleed": true,
//                 "allow_custom_colors": false,
//                 "deleted": false,
//                 "brand_id": null,
//                 "google_taxonomy_id": 5452,
//                 "imprint_area_details": null,
//                 "call_for_pricing": false,
//                 "click_through_boost": 100,
//                 "apply_vendor_hazmat_fee": false,
//                 "alternate_image_order": [
//                     194983,
//                     194984
//                 ],
//                 "elastic_search_index_date": "2025-03-10T19:07:31.188Z",
//                 "multiple_vendor_skus": false,
//                 "annual_update_notes": null,
//                 "handling_fee": "0.00",
//                 "shipping_zip": null,
//                 "product_parent_name": null,
//                 "swag_store_sku": "",
//                 "is_swag_store_copy": 0,
//                 "vendor_name": "Lion Circle Corp",
//                 "vendor_zip": "60629-5810",
//                 "taxonomy": "Arts & Entertainment>Party & Celebration>Party Supplies>Party Favors",
//                 "options": [
//                     {
//                         "id": 208220,
//                         "product_id": 37657,
//                         "create_date": "2014-07-18T20:27:21.000Z",
//                         "update_date": "2024-06-25T07:54:21.324Z",
//                         "display_order": 1,
//                         "min_qty": 100,
//                         "setups": 1,
//                         "side_1_colors": 0,
//                         "side_2_colors": 0,
//                         "side_1_full_color": true,
//                         "side_2_full_color": true,
//                         "flat_setup_fee": "0.00",
//                         "reorder_fee": "0.00",
//                         "description": "Full Color Imprint, Two Sides",
//                         "prices": [
//                             1.58,
//                             1.31,
//                             0.85,
//                             0.75,
//                             0.71,
//                             0.68,
//                             0.68
//                         ],
//                         "imprints": 1,
//                         "alternate_imprint_palette_id": null,
//                         "allow_custom_colors": false,
//                         "deleted": false,
//                         "alternate_imprint_palette": null
//                     }
//                 ],
//                 "subcategories": [
//                     {
//                         "id": 769,
//                         "create_date": "2015-07-22T19:17:50.000Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Full Color Hand Fans",
//                         "alt_name": null,
//                         "url_name": "full-color-hand-fans",
//                         "url_name_prev": null,
//                         "url_canonical": "/hand-fans/full-color-hand-fans/full-color-hand-fans",
//                         "description": "Full color hand fans are a great way to deliver a message to your audience.  Affordably priced with full color printing on one or two sides, our customized hand fans are great for concerts, festivals, sporting events, and more! ",
//                         "secondary_description": "Affordably priced with full color printing on one or two sides, our selection of custom printed hand fans is sure to meet your needs! In a rush? Check out our 24-Hour Rush Full Color Hand Fans - they're processed and shipped in just 24 hours! ",
//                         "category_id": 493,
//                         "display_order": 1,
//                         "active": true,
//                         "meta_title": "Full Color Hand Fans | PrintGlobe",
//                         "meta_description": "Full color hand fans are great giveaways for spring and summer events. Trust PrintGlobe to provide quality products and fast service, all at a low price!",
//                         "meta_keywords": "Full Color Hand Fans, Digitally Printed Hand Fans",
//                         "product_order_strategy": null,
//                         "url_redirects": "/hand-fans/hand-fans",
//                         "redirect_type": true,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Have a full color design or photograph that you'd like to show off on a fan? Our selection of full color hand fans are the most economical way to go! Affordably priced with vivid full color graphics on one or two sides, these high density 22 pt. poster board fans are a classic way to advertise. \n\nThese custom fans are available in a variety of shapes and come in two different styles: \n\n* __Econo hand fans:__ Our econo hand fans feature full color printing on one or both sides of the fan, but the stick is exposed on the backside of the fan. When advertising on both sides with econo hand fans, please be sure to leave room in your artwork for the stick. \n* __Sandwiched hand fans:__ Our sandwiched hand fans feature full color printing on one or both sides, and are \"sandwiched\" around the stick so it is not exposed. When advertising with sandwiched hand fans, you don't have to worry about leaving room in your artwork for the stick. \n\nWondering which style is best for your project? Really, it just depends on your artwork and budget! ! Both options feature a quality design and make classic advertising tools. Perfect for concerts, festivals, weddings, sporting events, and so much more, with a huge space for your logo or message, you can't go wrong with either one! \n\nWe've been helping people with their custom hand fan needs for over two decades! We take pride in our top-notch customer service and quality printing capabilities. For questions or help with your order, chat with us online or call us today! Our team of printing experts are here to help! \n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 0
//                     },
//                     {
//                         "id": 20003,
//                         "create_date": "2016-06-29T21:56:02.957Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Family Reunions",
//                         "alt_name": null,
//                         "url_name": "family-reunions",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Family reunions are the perfect time to put your family name on display! Print it on t-shirts, cups, sunglasses, koozies, and more. No matter how you celebrate, your family will love having custom items to set the event apart, and will surely be glad for personalized keepsakes to remember the occasion by for years to come. ",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Family Reunions | PrintGlobe",
//                         "meta_description": "Family Reunions",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Take pride in your family name and put it on display with our wide selection of custom printed apparel, sunglasses, cups, koozies, beach balls, balloons, ornaments, and so much more! Whether you’re looking to decorate an event space, show off your family name, or share a funny or sentimental story, family reunions and personalized products go hand-in-hand. Your family will love having custom family reunion supplies to help you stand out, and people will be grateful for mementos to remember the special occasion by. \n\nWith our large selection of custom family reunion supplies, we are confident that you will find the products you need at price you can afford. Hosting a reunion by the water? Our custom sunglasses, beach balls, koozies, and coolers make a fun choice. Celebrating your family around the holidays? Consider printing your family name on our great selection of personalized ornaments! Headed to the mountains? Check out our quality collection of blankets, coffee mugs, and tumblers. Whatever your theme, we’ve got the products you need to set your family reunion apart! \n\nFor more ideas or for help with your order, give us a call! Our team of printing experts are eager to help make your family reunion an affair to remember for years to come! ",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 2
//                     },
//                     {
//                         "id": 20005,
//                         "create_date": "2016-07-06T18:57:54.499Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Graduation",
//                         "alt_name": null,
//                         "url_name": "graduation",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Cap off the perfect year-end promotion with custom graduation promotional products. Great for schools and school sponsors, fraternities, sororities and alumni organizations, our graduation products are an excellent way to help remember the occasion by. ",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Graduation Promotions | PrintGlobe",
//                         "meta_description": "Graduation Promotions - Customized with your personal message.  PrintGlobe's got the selection at unbeatable prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Whether graduating from kindergarten or college, graduation ceremonies are occasions to celebrate and remember. Important for not just the graduate, but also for family and friends, graduation ceremonies deserve to be special, memorable events. Help make this happen by shopping our large selection of custom graduation products! \n\nWe offer everything you might need to make your graduation ceremony an event to remember. From custom printed napkins, plates, and cups for your graduation party, to balloons and banners for the ceremony, to fun trinkets and giveaways such as our custom hand fans, printed beach balls, koozies, and personalized sunglasses, we’ve got you covered every step of the way.   We even offer custom graduation cap signs and diploma certificate holders! With our huge quality selection, we are truly your one stop shop for all things custom graduation! \n\nOur products make setting your graduation event apart easy. Whether you are an individual wanting to add a special touch to your party, or a school looking for supplies for the big day, we’ve got you covered. All of our products come custom printed, so we can create a unique product for your individual needs! \n\nFor help choosing the best products for your event, or for questions about your order, give us a call! Our team of printing experts are eager to help! \n\nFrom your friends at PrintGobe, congratulations! \n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 1
//                     },
//                     {
//                         "id": 20006,
//                         "create_date": "2016-07-06T19:00:05.293Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Class Reunions",
//                         "alt_name": null,
//                         "url_name": "class-reunions",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Help your class reunion to be affair people will remember for years to come with our large selection of custom favors and party supplies. As a special occasion that only happens every five to ten years, setting the event apart with personalized favors and decorations is a great way to help people hold on to the memories until you all meet again.",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Class Reunions | PrintGlobe",
//                         "meta_description": "Class Reunion Promotions - Customized with your school logo.  PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Class reunions are an excellent time to reconnect with classmates and old friends – help people to celebrate and remember the occasion by printing your class information on our huge selection of class reunion supplies!\n\nOur class reunion supplies come in all shapes and sizes! While personalized t-shirts are our class reunion best sellers, we also see a lot of orders for custom koozies, reusable water bottles, hats, and sunglasses. Affordable items like these are a great way to mark the occasion and make it special, while staying on budget. Other unique ways to mark the occasion is with our large selection of custom printed napkins, plates, and drinkware. We offer a great selection of elegant glassware for formal parties, as well as several disposable options for more casual affairs. Whatever your needs, we’ve got the products your after to make your class reunion one to remember! \n\nWhether you want to print your school logo, your class slogan, a photograph, or maybe just your graduating year, our personalization options are endless! For help, give us a call! Our team of printing experts are eager to help make your reunion an affair to remember for years to come! \n\n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 4
//                     },
//                     {
//                         "id": 20007,
//                         "create_date": "2016-07-06T19:01:20.032Z",
//                         "update_date": "2024-07-19T09:35:33.130Z",
//                         "name": "Weddings",
//                         "alt_name": null,
//                         "url_name": "weddings",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Your wedding will be one of the most memorable days of your life, so help your guests to remember the occasion by leaving a special touch on all of your wedding details. With our wide selection of save the date magnets, wedding matches, invitations, personalized wedding favors, and more, we’ve got you covered from engagement to the moment you say “I do.”",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Wedding Promotions | PrintGlobe",
//                         "meta_description": "Wedding Promotions - Customized with your logo.  PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Personalized wedding supplies are the perfect way to set your event apart! Your wedding will be one of the most memorable days of your life, so help your guests to remember the occasion by leaving a special touch on your wedding details.With our wide selection of save the date magnets, wedding matches, invitations, personalized wedding favors, and more, we’ve got your covered from engagement to the moment you say “I do.\" \n\nGuests will love personalized mason jars or wedding mints, and out of town visitors are sure to feel appreciated when greeted with a  wedding welcome bag . Our custom hand fans are great for outdoor weddings, and our personalized wedding napkins help to fulfill a classic wedding detail. Add a special touch at your reception with personalized wine glasses or champagne flutes, and send people off at the end of the night with our quality selection of wedding party favors. \n\nWe know how stressful planning a wedding can be, but with a friendly and knowledgeable staff here to help, we’ll make your wedding shopping experience exciting and easy. Just call 1-800-989-2181 or chat with us online during the hours of 8 AM to 6 PM to discuss your needs and get expert suggestions from our helpful team! \n\nStill not seeing what you're after? Head on over to our  Wedding Products  page to see our full personalized wedding supplies selection! \n\nCongratulations from your friends at PrintGlobe! \n\n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2024-07-19T13:07:40.766Z",
//                         "landing_page_name": null,
//                         "product_display_order": 3
//                     },
//                     {
//                         "id": 20009,
//                         "create_date": "2016-07-06T19:06:53.137Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "July 4th Promotions",
//                         "alt_name": null,
//                         "url_name": "july-4th",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "PrintGlobe has everything you need to advertise your brand at Fourth of July celebrations except the fireworks. But you can spark interest on your own with our selection of July 4th decorations and promotional items such as printed fans, custom sunglasses, water bottles and even seating!",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "July 4th Promotions | PrintGlobe",
//                         "meta_description": "July 4th Promotions - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Show your pride for the great red, white, and blue and celebrate independence with our explosive selection of 4th of July supplies! From backyard barbecues to city parades, we’ve got just the products you need to spark interest in your brand! \n\nOur custom sunglasses, towels, beach balls, and coolers are perfect for showing off your logo at the beach, lake, river, or pool, and our personalized koozies, water bottles, picnic blankets, and chairs are perfect for 4th of July parties and firework displays. Keep cool and show your USA pride with our patriotic selection of custom hand fans, and join the celebration with our fun selection of printed noisemakers. Just shy of the fireworks, we’ve got everything you need to make your celebration fun! We even offer printed napkins and disposable plates, cups, and table cloths to cover the party basics. When it comes to 4th of July supplies, we've truly got your covered! \n\nIf you’re not seeing what you’re after, give us a call! With thousands of quality, custom items available, we’re confident that we can help you find just the product you’re after to make your Independence Day celebration a success! ",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 1
//                     },
//                     {
//                         "id": 20010,
//                         "create_date": "2016-07-06T19:09:11.980Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Memorial Day",
//                         "alt_name": null,
//                         "url_name": "memorial-day",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Shop our quality selection of custom Memorial Day products, perfect for your big sale or Memorial Day event.  We offer custom printed patriotic hand fans, balloons, picnic blankets, and more.",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Memorial Day Promotions | PrintGlobe",
//                         "meta_description": "Memorial Day Promotions - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": null,
//                         "display_long_desc": false,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 1
//                     },
//                     {
//                         "id": 20012,
//                         "create_date": "2016-07-06T19:12:47.099Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "St. Patrick’s Day",
//                         "alt_name": null,
//                         "url_name": "st-patricks-day",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "The celebration of St. Patrick on March 17th has become a worldwide tradition that boasts thousands of parades and parties. Trust PrintGlobe as your source for custom St. Patrick’s Day supplies and all things Kelly green.",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "St. Patrick’s Day | PrintGlobe",
//                         "meta_description": "St. Patrick’s Day - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Let the luck of the Irish be with your next promotion by shopping PrintGlobe for all of your St. Patrick’s Day needs! \n\nNeed coasters or koozies for your bar or party? We’ve got ‘em! How about beer glasses for your pub? We’ve got those too! Need some Kelly green napkins for your dinner or event? We’ve got you covered! How about party favors and giveaways like shamrock shaped hand fans and key chains? Look no further! \n\nFrom stout glasses, to party hats, to tote bags and more, we offer thousands of products, and hundreds of things in green. No what kind of St. Patrick's Day supplies you're after, we’ve got what you need!\n\nEverything we sell comes custom printed, so we can easily highlight your unique design. Whether you want to print a one color logo or a full color photograph, we’ve got thousands of products for you to work with, and our team of printing experts are here to help! \n\nWith our quality St. Patrick's Day supplies, you’re promotion is sure to be a lucky one! \n\n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 0
//                     },
//                     {
//                         "id": 20015,
//                         "create_date": "2016-07-06T19:29:03.075Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Bars & Restaurants",
//                         "alt_name": null,
//                         "url_name": "bars-restaurants",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Whether you are looking to add a special touch to your establishment or to share a message with your customers, our wide selection of custom coasters and printed barware make great promotional pieces for your bar or restaurant. Shop from our quality collection of coasters, beer glasses, Moscow Mule mugs, napkins, and more, and start advertising your bar or restaurant in style today! ",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Bars & Restaurant Promos | PrintGlobe",
//                         "meta_description": "Bars & Restaurant Promos - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": null,
//                         "display_long_desc": false,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 3
//                     },
//                     {
//                         "id": 20016,
//                         "create_date": "2016-07-06T19:30:51.704Z",
//                         "update_date": "2024-07-19T09:35:33.130Z",
//                         "name": "Tailgating",
//                         "alt_name": null,
//                         "url_name": "tailgating",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Tailgating parties are the perfect opportunity to advertise your brand. Nearly as important as the games themselves, the “go big or go home” attitude of these parties makes for a prime time to put your logo in the center of a large crowd. Shop our large selection of event tents, folding chairs, pennants, foam fingers, pom poms, and more! ",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Tailgating | PrintGlobe",
//                         "meta_description": "Tailgating Promos  - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Good food, refreshing drinks, excellent company, crisp weather, and football… what is there not to love about tailgating?! Much anticipated fall events, tailgating parties can be nearly just as fun as the games themselves, and with our quality selection of custom tailgating supplies, we’ve got what you need to really set your party apart. \n\nFrom establishing the perfect setting with custom event tents, folding chairs, and cornhole sets, to making it a comfortable space with sweatshirt blankets and hand fans, we’ve truly got it all. We’ve got custom napkins, koozies, stadium cups, plates, disposable table cloths, ice chests, and more! We’ve even got a large selection of spirit items like custom pom poms, megaphones, foam fingers, mini sports balls, and noisemakers to help keep things fun. With tailgating supplies from PrintGlobe, you can rest easy knowing that your party will be a good time! For more ideas about some of our favorite tailgating supplies, be sure to check out our  blog ! \n\nAll of our products come custom printed, so if you’re looking for an easy way to really personalize your tailgating party, you’ve come to the right place! Our products are perfect for putting your team or school name on display, and are also a great way to highlight the name of your event, business, sorority, fraternity, or club.  \n\nFor help with your order, don’t hesitate to chat with us online or to give us a call. We’ve been in the printing business for over 20 years and are eager to help! \n\nFrom your friends at PrintGlobe, go team! \n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2024-07-19T13:07:40.766Z",
//                         "landing_page_name": null,
//                         "product_display_order": 1
//                     },
//                     {
//                         "id": 20017,
//                         "create_date": "2016-07-06T20:25:14.685Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Trade Shows & Conventions",
//                         "alt_name": null,
//                         "url_name": "trade-shows-conventions",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Trade shows and conventions are extremely valuable resources and are a great place to advertise your brand and to earn yourself new business.  Shop our wide selection of trade show and conference swag such as banners, pens, bags, and other giveaways and supplies to make your trade show involvement a success!",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Trade Shows / Conventions | PrintGlobe",
//                         "meta_description": "Trade Shows / Conventions - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": null,
//                         "display_long_desc": false,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 2
//                     },
//                     {
//                         "id": 20019,
//                         "create_date": "2016-07-07T18:05:39.439Z",
//                         "update_date": "2021-10-14T14:30:39.658Z",
//                         "name": "Awareness Products",
//                         "alt_name": null,
//                         "url_name": "awareness-products",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Whether trying to raise awareness for cancer, a disability, or some other notable cause, raising awareness with promotional products is an excellent way to bring attention to issues that matter. From awareness fundraisers, to event giveaways, to donor gifts, we’ve got a great selection of products to help bring attention to your cause! ",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Awareness Products | PrintGlobe",
//                         "meta_description": "Awareness Products - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": null,
//                         "display_long_desc": false,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2023-09-12T10:38:34.419Z",
//                         "landing_page_name": null,
//                         "product_display_order": 24
//                     },
//                     {
//                         "id": 20021,
//                         "create_date": "2016-07-07T18:07:56.850Z",
//                         "update_date": "2024-07-19T09:35:33.130Z",
//                         "name": "Political Campaigns",
//                         "alt_name": null,
//                         "url_name": "political-campaigns",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "From presidential candidates to federal and state representatives, to contenders for school board, judge, or sheriff, custom campaign materials are an integral part to any election. We offer a large selection of brochures, buttons, lapel stickers, yard signs, and more to help make your next political campaign a success! ",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Political Campaigns | PrintGlobe",
//                         "meta_description": "Political Campaigns - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Custom campaign materials are fundamental to establishing name recognition and for raising support. Vital every phase of an election, it’s important to understand the influence custom campaign materials can play from the very beginning of any campaign. To ensure the greatest possibility for success for your candidate, we offer campaign materials for every type of election, from school board contenders to presidential candidates!  \n\nDon’t underestimate the importance of fundamental corporate identity pieces such as letterheads, business cards, and donor envelopes, or brochures, postcards, and political palm cards. We also offer other campaign staples such as lapel stickers, buttons, t-shirts, vinyl banners, political posters, plastic yard signs, and more! If you are looking for giveaways or campaign fundraising pieces, be sure to check out our campaign pens, tote bags, coffee mugs, hand fans, and rally signs. We truly offer it all! \n\nTried and true promotional pieces, our campaign materials are sure to lead your candidate on a road to success! For additional ideas about how to use our campaign materials, be sure to check out our  blog  , or give us a call. Our team of printing experts are here to help! \n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2024-07-19T13:07:40.766Z",
//                         "landing_page_name": null,
//                         "product_display_order": 3
//                     },
//                     {
//                         "id": 20022,
//                         "create_date": "2016-07-07T19:02:49.578Z",
//                         "update_date": "2024-07-19T09:35:33.130Z",
//                         "name": "School Spirit Promotions",
//                         "alt_name": null,
//                         "url_name": "school-spirit-promotions",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Show off your school spirit with our great selection of school spirit promotional products! Take your message on the road with our car flags and bumper stickers, or shout it loud with our custom printed megaphones. Get people cheering with pompoms and foam fingers, and constantly remind people of your brand by advertising with sport schedule magnets. Whatever you’re after, we’ve got just the product to help you show pride for your team, school, club, or brand! ",
//                         "secondary_description": null,
//                         "category_id": 88,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "School Spirit Promotions | PrintGlobe",
//                         "meta_description": "School Spirit Promotions - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "School spirit products are the perfect way to put your name on school campuses all around town! We offer hundreds of school spirit products perfect for showing pride for your team, school, club, sorority, fraternity, or brand. From taking your message on the road with custom car flags and bumper stickers, to getting people cheering in the stands with printed megaphones and noisemakers, we’ve got everything you need to show your spirit! \n\nCustom pennants make a classic school promotion and are an affordable way to display your school name, team mascot, or club information. Perfect for gift shops, fundraisers, welcome gifts, giveaways, and more, our personalized pennants will look great hanging in a dorm room, framed at home, or waved in the stands. Another classic item to wave around in the stands are custom pom poms! The quintessential choice for school spirit promotions, our pom poms come in a plethora of color choices to match your school or team. Looking for another classic option? Why not advertise with custom foam fingers and spirit hands?! We’ve got everything from the classic #1 hand design to foam paws and defense mitts. \n\nOur selection is extensive, but don’t feel overwhelmed! Our team of printing experts are here to make your shopping experience as easy as possible! Feel free to reach out to us online, call us, or check out our  blog  for more ideas. \n\n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2024-07-19T13:07:40.766Z",
//                         "landing_page_name": null,
//                         "product_display_order": 21,
//                         "primary_image": {
//                             "id": 271711,
//                             "image_type": "primary",
//                             "url_path": "/images/subcategories/ID20022-school_spirit_promotions-primary.jpg",
//                             "alt_text": "School Spirit Promotions",
//                             "navigate": null
//                         }
//                     },
//                     {
//                         "id": 20023,
//                         "create_date": "2016-07-13T21:01:51.137Z",
//                         "update_date": "2024-07-19T09:35:33.130Z",
//                         "name": "Festivals & Concerts",
//                         "alt_name": null,
//                         "url_name": "festivals-and-concerts",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "Exciting social gatherings, festivals and concerts are perfect occasions to advertise your business. Whether you are looking for fun giveaways like custom printed koozies or sunglasses, or event supplies like wine tasting glasses or personalized beer mugs, we’ve got what you need to put your logo on display and to help people form a positive association with your brand!",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Festivals & Concerts | PrintGlobe",
//                         "meta_description": "Personalized festival and concert supplies and giveaways to help you advertise. Shop PrintGlobe today and save! ",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "From concerts, to food, beer, and wine festivals, to art and craft events, we’ve got what you need to affordably share your message and put you logo in people’s hands! With products for every occasion, we are your one-stop-shop for custom festival supplies. From printing your logo on banners and event tents, to showcasing your design on water bottles, koozies, or tattoos, we offer a huge selection of personalized products perfect for putting your brand in the center of a large crowd. \n\nPerfect for outdoor events or major music festivals such as Austin City Limits, Lollapalooza, or Bonnaroo, our custom sunglasses, water bottles, rain ponchos, and fanny packs make great advertisements or booth giveaways. Looking for items for a food, beer, or wine festival? Check out our quality selection of printed wine glasses, beer tasting glasses, plastic beer steins, napkins, and disposable food containers and cups. Need something  for your next arts or crafts fair? Reusable shopping bags are always a smart choice! \n\nWhether you are looking to print a one color logo or a full color photograph, all of our products come custom printed, so whatever the design you're after, we can help you create the look you want and need! We make buying custom festival supplies a breeze! \n\nLooking for additional ideas or need help figuring out how to best use our festival and concert products to advertise your brand? Be sure to check out our  blog  to learn more about our most popular festival promotions and giveaways. Or, if you're planning to attend a festival soon, be sure to check out our festival survival guide, available  here  . Trust us, you'll be thankful you did after a long weekend of festival fun! \n\n\n\n\n\n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2024-07-19T13:07:40.766Z",
//                         "landing_page_name": null,
//                         "product_display_order": 2
//                     },
//                     {
//                         "id": 20002,
//                         "create_date": "2016-06-29T21:52:51.072Z",
//                         "update_date": "2024-06-25T07:52:31.504Z",
//                         "name": "Birthdays",
//                         "alt_name": null,
//                         "url_name": "birthdays",
//                         "url_name_prev": null,
//                         "url_canonical": null,
//                         "description": "A lead supplier in custom party supplies, we can help make your next birthday celebration a success! Whether you’re searching for printed cups, plates, and napkins, or something more festive like balloons or noisemakers, we’ve got just what you need to have a good time!",
//                         "secondary_description": null,
//                         "category_id": null,
//                         "display_order": null,
//                         "active": true,
//                         "meta_title": "Birthdays | PrintGlobe",
//                         "meta_description": "Customized birthday promotional products to make your special day fantastic.",
//                         "meta_keywords": null,
//                         "product_order_strategy": null,
//                         "url_redirects": null,
//                         "redirect_type": null,
//                         "redirect_date": null,
//                         "redirect_notes": null,
//                         "deleted": false,
//                         "long_desc": "Whether turning 1, 10, 50, or 100, birthdays are a time to celebrate! Make your party a smashing success by shopping our huge selection of custom birthday party supplies! \n\nOur custom printed balloons make excellent party decorations, and our personalized cups, napkins, and plates are a great way to serve up drinks and cake. Our printed noisemakers make fun party favors, and our custom hand fans are a unique way to celebrate the special birthday boy or girl. \n\nOur printing capabilities are vast and the personalization options for our products are endless, making it a breeze for you to add your special touch to your next birthday celebration. Just pick a product and send us your information or design and our team of printing experts will handle the hard work for you! If you can’t decide what product best suits your needs, give us a call! Our team of dedicated account managers are here to help and are eager to make your shopping experience as easy as possible.  We take pride in our quality products and top notch customer service, and look forward to helping you with your birthday supply order today! \n",
//                         "display_long_desc": true,
//                         "display_banner_image": true,
//                         "elastic_search_index_date": "2024-06-25T13:07:34.043Z",
//                         "landing_page_name": null,
//                         "product_display_order": 71
//                     }
//                 ],
//                 "parents": [
//                     [
//                         {
//                             "name": "Business Printing",
//                             "path": "/business-printing",
//                             "active": true
//                         },
//                         {
//                             "name": "Post-it® Notes and Notepads",
//                             "path": "/post-it-notes-and-notepads",
//                             "active": true
//                         },
//                         {
//                             "name": "100 Sheet Post-it Notes",
//                             "path": "/100-sheet-post-it-notes",
//                             "active": false
//                         },
//                         {
//                             "name": "School Spirit Promotions",
//                             "path": "/school-spirit-promotions",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Promotional Products",
//                             "path": "/promotional-products",
//                             "active": true
//                         },
//                         {
//                             "name": "Hand Fans",
//                             "path": "/hand-fans",
//                             "active": true
//                         },
//                         {
//                             "name": "Full Color Hand Fans",
//                             "path": "/full-color-hand-fans",
//                             "active": true
//                         },
//                         {
//                             "name": "Full Color Hand Fans",
//                             "path": "/full-color-hand-fans",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Birthdays",
//                             "path": "/birthdays",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Festivals & Concerts",
//                             "path": "/festivals-and-concerts",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Political Campaigns",
//                             "path": "/political-campaigns",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Awareness Products",
//                             "path": "/awareness-products",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Trade Shows & Conventions",
//                             "path": "/trade-shows-conventions",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Tailgating",
//                             "path": "/tailgating",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Bars & Restaurants",
//                             "path": "/bars-restaurants",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "St. Patrick’s Day",
//                             "path": "/st-patricks-day",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Memorial Day",
//                             "path": "/memorial-day",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "July 4th Promotions",
//                             "path": "/july-4th",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Weddings",
//                             "path": "/weddings",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Class Reunions",
//                             "path": "/class-reunions",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Graduation",
//                             "path": "/graduation",
//                             "active": true
//                         }
//                     ],
//                     [
//                         {
//                             "name": "Family Reunions",
//                             "path": "/family-reunions",
//                             "active": true
//                         }
//                     ]
//                 ],
//                 "features": [
//                     {
//                         "id": 26,
//                         "name": "Full Color",
//                         "display_pricing_grid": false,
//                         "display_as_banner": false,
//                         "pricing_grid_text": null,
//                         "banner_rgb": "598300"
//                     },
//                     {
//                         "id": 27,
//                         "name": "Top Seller",
//                         "display_pricing_grid": false,
//                         "display_as_banner": true,
//                         "pricing_grid_text": null,
//                         "banner_rgb": "D22D2E"
//                     },
//                     {
//                         "id": 2,
//                         "name": "Made in USA",
//                         "display_pricing_grid": false,
//                         "display_as_banner": false,
//                         "pricing_grid_text": null,
//                         "banner_rgb": "D22D2E"
//                     }
//                 ],
//                 "firstSubCategory": {
//                     "id": 20022,
//                     "create_date": "2016-07-07T19:02:49.578Z",
//                     "update_date": "2024-07-19T09:35:33.130Z",
//                     "name": "School Spirit Promotions",
//                     "alt_name": null,
//                     "url_name": "school-spirit-promotions",
//                     "url_name_prev": null,
//                     "url_canonical": null,
//                     "description": "Show off your school spirit with our great selection of school spirit promotional products! Take your message on the road with our car flags and bumper stickers, or shout it loud with our custom printed megaphones. Get people cheering with pompoms and foam fingers, and constantly remind people of your brand by advertising with sport schedule magnets. Whatever you’re after, we’ve got just the product to help you show pride for your team, school, club, or brand! ",
//                     "secondary_description": null,
//                     "category_id": 88,
//                     "display_order": null,
//                     "active": true,
//                     "meta_title": "School Spirit Promotions | PrintGlobe",
//                     "meta_description": "School Spirit Promotions - Customized with your logo. PrintGlobe's got the selection of promotional products offered at low, low prices.",
//                     "meta_keywords": null,
//                     "product_order_strategy": null,
//                     "url_redirects": null,
//                     "redirect_type": null,
//                     "redirect_date": null,
//                     "redirect_notes": null,
//                     "deleted": false,
//                     "long_desc": "School spirit products are the perfect way to put your name on school campuses all around town! We offer hundreds of school spirit products perfect for showing pride for your team, school, club, sorority, fraternity, or brand. From taking your message on the road with custom car flags and bumper stickers, to getting people cheering in the stands with printed megaphones and noisemakers, we’ve got everything you need to show your spirit! \n\nCustom pennants make a classic school promotion and are an affordable way to display your school name, team mascot, or club information. Perfect for gift shops, fundraisers, welcome gifts, giveaways, and more, our personalized pennants will look great hanging in a dorm room, framed at home, or waved in the stands. Another classic item to wave around in the stands are custom pom poms! The quintessential choice for school spirit promotions, our pom poms come in a plethora of color choices to match your school or team. Looking for another classic option? Why not advertise with custom foam fingers and spirit hands?! We’ve got everything from the classic #1 hand design to foam paws and defense mitts. \n\nOur selection is extensive, but don’t feel overwhelmed! Our team of printing experts are here to make your shopping experience as easy as possible! Feel free to reach out to us online, call us, or check out our  blog  for more ideas. \n\n",
//                     "display_long_desc": true,
//                     "display_banner_image": true,
//                     "elastic_search_index_date": "2024-07-19T13:07:40.766Z",
//                     "landing_page_name": null,
//                     "product_display_order": 21,
//                     "primary_image": {
//                         "id": 271711,
//                         "image_type": "primary",
//                         "url_path": "/images/subcategories/ID20022-school_spirit_promotions-primary.jpg",
//                         "alt_text": "School Spirit Promotions",
//                         "navigate": null
//                     }
//                 },
//                 "alternates": [
//                     {
//                         "id": 1374,
//                         "url_path": "/images/products/ID37657-full_color_econo_bread_slice_hand_fans-alt_image_1.jpg",
//                         "alt_text": "Full Color Econo Bread Slice Hand Fans with your custom logo",
//                         "title": "Full Color Econo Bread Slice Hand Fans"
//                     },
//                     {
//                         "id": 1375,
//                         "url_path": "/images/products/ID37657-full_color_econo_bread_slice_hand_fans-alt_image_2.jpg",
//                         "alt_text": "Full Color Econo Bread Slice Hand Fans with your custom logo",
//                         "title": "Full Color Econo Bread Slice Hand Fans"
//                     }
//                 ],
//                 "middle": {
//                     "id": 273278,
//                     "create_date": "2024-06-25T07:54:21.823Z",
//                     "update_date": "2024-12-26T11:29:43.827Z",
//                     "product_id": 37657,
//                     "alt_text": "Full Color Econo Bread Slice Hand Fans",
//                     "url_path": "/images/products/pid37657-breadslice_hand_fan-2.jpg",
//                     "image_type": "middle",
//                     "navigate": null
//                 },
//                 "primary_image": {
//                     "id": 273277,
//                     "create_date": "2024-06-25T07:54:21.820Z",
//                     "update_date": "2024-12-26T11:32:54.159Z",
//                     "product_id": 37657,
//                     "alt_text": "Full Color Econo Bread Slice Hand Fans",
//                     "url_path": "/images/products/hires/pid37657-breadslice_hand_fan.jpg",
//                     "image_type": "primary",
//                     "navigate": null
//                 },
//                 "thumbnail": {
//                     "id": 273279,
//                     "create_date": "2024-06-25T07:54:21.824Z",
//                     "update_date": "2024-12-26T11:33:49.898Z",
//                     "product_id": 37657,
//                     "alt_text": "Full Color Econo Bread Slice Hand Fans",
//                     "url_path": "/images/products/thumbs/pid37657-breadslice_hand_fan-th.jpg",
//                     "image_type": "thumbnail",
//                     "navigate": null
//                 },
//                 "discount": 0,
//                 "special": null,
//                 "vendor": {
//                     "id": 414,
//                     "create_date": "2016-01-29T23:21:28.000Z",
//                     "update_date": "2017-04-06T16:04:07.378Z",
//                     "annual_update_date": "2017-01-25T00:00:00.000Z",
//                     "asi_number": "67620",
//                     "name": "Lion Circle Corp",
//                     "deleted": false,
//                     "address": "4600 W. 72nd St.",
//                     "city": "Chicago",
//                     "state": "IL",
//                     "zip": "60629-5810",
//                     "url": "www.lioncircle.com",
//                     "pms_upcharge": "15.00",
//                     "phone": "--",
//                     "contact_name": null,
//                     "contact_email": "info@lioncircle.com",
//                     "vendor_code": "LCC",
//                     "cs_open_time": "18:00:00",
//                     "cs_close_time": "18:00:00",
//                     "pricing_scheme": "NQP @ 500; Starts @ 3rd Column; New Set-up policy of $40 applied",
//                     "price_multiplier": "1.020",
//                     "hazmat_fee": "0.00",
//                     "additional_handling_fee": "0.00",
//                     "additional_handling_type": "per_case",
//                     "annual_update_notes": null,
//                     "price_multiplier_notes": null,
//                     "cm_id": null,
//                     "is_sample_button_excluded": false
//                 }
//             },
//             "addons": [],
//             "isAbleToCheckout": true,
//             "subtotal": 158,
//             "total": 198
//         }
//     ],
//     "contactInfo": {
//         "firstName": "Engeny",
//         "lastName": "Danilovich",
//         "email": "kitaety111111@gmail.com",
//         "phone": "+11234567890",
//         "isNewsletterSubscriber": false,
//         "net_id": null
//     },
//     "loggedIn": true,
//     "adminLoggedIn": true,
//     "modifyCartItem": {},
//     "orders": [],
//     "paymentMethods": [],
//     "recentItems": [
//         {
//             "id": 29415,
//             "url_name": "service-invoice-forms-laser",
//             "name": "Service Invoice Forms (Laser)",
//             "lowest_price": 0.13,
//             "product_price": 0.13,
//             "public_sku": "FOR0021",
//             "primary_image": "/images/products/quickbooks%20service%20invoice%20forms_lg.gif",
//             "thumbnail": "/images/products/quickbooks%20service%20invoice%20forms_sm.gif"
//         },
//         {
//             "id": 7952,
//             "url_name": "element-pens",
//             "name": "Element Pens",
//             "lowest_price": 0.45,
//             "product_price": 0.45,
//             "public_sku": "PEN0208",
//             "primary_image": "/images/products/hires/pid7952-element_pens.jpg",
//             "thumbnail": "/images/products/thumbs/pid7952-element_pens-12.jpg"
//         },
//         {
//             "id": 26192,
//             "url_name": "folding-chairs-carrying-bag",
//             "name": "Folding Chairs with Carrying Bag",
//             "lowest_price": 16.04,
//             "product_price": 16.04,
//             "public_sku": "SPI0220",
//             "primary_image": "/images/products/ID26192-folding_chairs_carrying_bag-primary.jpg",
//             "thumbnail": "/images/products/thumbs/pid26192-folding_chair_w_carrying_bag-th.jpg"
//         },
//         {
//             "id": 38574,
//             "url_name": "croakies",
//             "name": "Croakies&reg;",
//             "lowest_price": 2.81,
//             "product_price": 2.81,
//             "public_sku": "SUN0075",
//             "primary_image": "/images/products/ID38574-croakies_reg-primary.jpg",
//             "thumbnail": "/images/products/thumbs/pid38574-custom-croakies-regular_sm.jpg"
//         },
//         {
//             "id": 37657,
//             "url_name": "full-color-bread-slice-hand-fans-low-minimum-econo",
//             "name": "Full Color Econo Bread Slice Hand Fans",
//             "lowest_price": 0.68,
//             "product_price": 0.68,
//             "public_sku": "FAN0243",
//             "primary_image": "/images/products/hires/pid37657-breadslice_hand_fan.jpg",
//             "thumbnail": "/images/products/thumbs/pid37657-breadslice_hand_fan-th.jpg"
//         },
//         {
//             "id": 11476,
//             "url_name": "paper-popcorn-bags-white-kraft",
//             "name": "4\" x 8\" White Kraft Popcorn Bags",
//             "lowest_price": 0.17,
//             "product_price": 0.17,
//             "public_sku": "BAG0386",
//             "primary_image": "/images/products/hires/pid11476-white_kraft_popcorn_bags_lg.jpg",
//             "thumbnail": "/images/products/thumbs/pid11476-white_kraft_popcorn_bags_sm.jpg"
//         },
//         {
//             "id": 38807,
//             "url_name": "classic-rume-tote-medium",
//             "name": "Classic Pink RuMe Tote - Mini",
//             "lowest_price": 5.41,
//             "product_price": 5.41,
//             "public_sku": "BAG0616",
//             "primary_image": "/images/products/hires/pid38807-5.jpg",
//             "thumbnail": "/images/products/thumbs/pid38807-120.jpg"
//         },
//         {
//             "id": 28501,
//             "url_name": "deluxe-wedding-luncheon-napkins-white-3-ply",
//             "name": "3-Ply White Wedding Luncheon Napkins",
//             "lowest_price": 0.15,
//             "product_price": 0.15,
//             "public_sku": "WED0071",
//             "primary_image": "/images/products/ID28501-deluxe_wedding_luncheon_napkins_white_3_ply-primary.jpg",
//             "thumbnail": "/images/products/ID28501-deluxe_wedding_luncheon_napkins_white_3_ply-thumbnail.jpg"
//         }
//     ],
//     "saved": [],
//     "last_cart": []
// }

export type ProfileContactInfo = {
    email: string | undefined;
};

export type ProfileState = {
    isLogin: boolean;
    contactInfo: ProfileContactInfo | null;
};